<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class beritaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('berita')->insert([
            [
                'judul' => 'Membangkitkan Semangat di Tengah Pandemi',
                'slug' => Str::slug('Membangkitkan Semangat di Tengah Pandemi'),
                'preview' => "Di masa pandemi ini, menjaga semangat dan motivasi menjadi sangat penting. Banyak kisah inspiratif yang bisa kita ambil pelajaran, salah satunya adalah perjuangan seorang ibu tunggal yang berhasil membuka berhasil membuka...",
                'konten' => "[h]Mengatasi Tantangan Pandemi[/h]\n[p]Pandemi COVID-19 telah membawa banyak tantangan bagi masyarakat di seluruh dunia. Kehidupan sehari-hari berubah drastis, dan banyak orang yang harus menyesuaikan diri dengan kondisi baru. Namun, di balik semua kesulitan ini, kita juga melihat banyak kisah inspiratif tentang ketahanan dan semangat juang. Salah satu kisah tersebut adalah tentang seorang ibu tunggal yang mampu bertahan dan bangkit di tengah pandemi ini.[/p]\n[p]Ibu tunggal ini harus menghadapi banyak rintangan, termasuk kehilangan pekerjaan dan harus mengurus anak-anaknya sendirian. Namun, dia tidak menyerah. Dengan tekad yang kuat, dia mencari cara untuk tetap bisa memberikan yang terbaik untuk keluarganya. Dia mulai berjualan online dan belajar keterampilan baru untuk mendukung usahanya.[/p]\n[p]Kisahnya menunjukkan bahwa meskipun kita dihadapkan pada situasi yang sulit, kita selalu memiliki pilihan untuk bangkit dan mencari solusi. Dengan semangat dan determinasi, kita bisa menghadapi segala tantangan yang ada.[/p]\n[h]Kekuatan Dalam Kebersamaan[/h]\n[p]Pandemi juga mengajarkan kita tentang pentingnya kebersamaan dan saling mendukung. Di berbagai tempat, kita melihat komunitas yang saling membantu dan berbagi sumber daya. Solidaritas menjadi kunci dalam menghadapi masa-masa sulit ini. Banyak organisasi dan individu yang bekerja sama untuk membantu mereka yang paling membutuhkan.[/p]\n[p]Di lingkungan sekitar, kita melihat banyak inisiatif lokal yang muncul. Misalnya, tetangga saling membantu dengan berbagi makanan dan kebutuhan sehari-hari. Komunitas online juga berkembang pesat, dengan banyak orang yang bergabung dalam kelompok-kelompok dukungan untuk memberikan semangat dan bantuan.[/p]\n[p]Kebersamaan ini menunjukkan bahwa kita tidak sendirian dalam menghadapi pandemi. Dengan bekerja sama dan saling mendukung, kita bisa mengatasi berbagai rintangan yang ada. Kebersamaan dan solidaritas menjadi kekuatan kita dalam menghadapi masa sulit ini.[/p]\n[h]Melihat Masa Depan dengan Optimis[/h]\n[p]Meskipun pandemi ini membawa banyak kesulitan, kita juga perlu melihat masa depan dengan optimis. Banyak perubahan yang terjadi selama pandemi yang bisa menjadi peluang untuk perbaikan. Misalnya, teknologi semakin berkembang pesat dan memungkinkan kita untuk bekerja dan belajar dari rumah. Ini bisa menjadi kesempatan untuk mengembangkan keterampilan baru dan mencari peluang baru.[/p]\n[p]Selain itu, pandemi juga mengajarkan kita untuk lebih menghargai kesehatan dan kebersihan. Kebiasaan baik yang kita kembangkan selama pandemi, seperti mencuci tangan dan menjaga jarak sosial, bisa terus kita lakukan untuk menjaga kesehatan kita di masa depan. Ini adalah pelajaran berharga yang bisa kita ambil dari situasi sulit ini.[/p]\n[p]Dengan melihat masa depan dengan optimis, kita bisa menemukan motivasi untuk terus maju. Meskipun jalan di depan mungkin masih penuh tantangan, kita bisa melewatinya dengan semangat dan keyakinan bahwa kita bisa bangkit dan menjadi lebih kuat dari sebelumnya.[/p]",
                'kategori' => 'Motivasi',
                'thumbnail' => "https://img.freepik.com/free-photo/asian-female-casual-shirt-wear-facial-mask-virus-protection-new-normal-lifestyle-sit-relax-window-glass-with-reflect-garden-outside-health-ideas-concept_609648-1241.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Pemerintah Terbitkan Regulasi Baru untuk Lindungi UMKM',
                'slug' => Str::slug('Pemerintah Terbitkan Regulasi Baru untuk Lindungi UMKM'),
                'preview' => 'Dalam upaya mendukung perkembangan Usaha Mikro, Kecil, dan Menengah (UMKM), pemerintah mengeluarkan peraturan baru yang bertujuan untuk memberikan perlindungan hukum yang lebih kuat bagi pelaku UMKM di seluruh Indonesia...',
                'konten' => "[h]Regulasi Baru untuk UMKM[/h]\n[p]Pemerintah telah mengeluarkan peraturan baru yang bertujuan untuk melindungi dan mendukung perkembangan Usaha Mikro, Kecil, dan Menengah (UMKM) di seluruh Indonesia. Peraturan ini mencakup berbagai aspek, mulai dari perlindungan hukum hingga bantuan finansial bagi pelaku UMKM. Dengan adanya regulasi ini, diharapkan UMKM dapat lebih mudah mendapatkan akses ke sumber daya yang mereka butuhkan untuk berkembang.[/p]\n[p]Salah satu poin penting dalam regulasi ini adalah peningkatan akses UMKM terhadap sumber daya dan teknologi yang diperlukan untuk berkembang. Pemerintah juga menyediakan berbagai insentif pajak dan bantuan langsung untuk membantu UMKM yang terdampak pandemi COVID-19. Ini menunjukkan komitmen pemerintah dalam mendukung sektor UMKM sebagai salah satu pilar utama perekonomian nasional.[/p]\n[p]Selain itu, regulasi baru ini juga mencakup perlindungan hukum yang lebih kuat bagi UMKM. Dengan adanya perlindungan ini, diharapkan para pelaku UMKM dapat menjalankan usahanya dengan lebih aman dan nyaman. Perlindungan ini mencakup berbagai aspek, mulai dari hak kekayaan intelektual hingga perlindungan terhadap praktik bisnis yang tidak sehat. Semua ini bertujuan untuk menciptakan lingkungan bisnis yang lebih adil dan kondusif bagi perkembangan UMKM.[/p]\n[h]Dukungan Finansial dan Teknologi[/h]\n[p]Untuk mendukung UMKM yang terdampak pandemi, pemerintah juga menyediakan berbagai program bantuan finansial. Bantuan ini mencakup pinjaman dengan bunga rendah, hibah, serta pelatihan dan pendampingan untuk membantu UMKM mengembangkan usahanya. Program ini diharapkan dapat memberikan dorongan bagi UMKM untuk bangkit kembali dan bahkan tumbuh lebih kuat di masa depan.[/p]\n[p]Di samping itu, akses terhadap teknologi juga menjadi fokus utama dalam regulasi baru ini. Pemerintah berusaha untuk menyediakan berbagai platform digital yang dapat membantu UMKM dalam memasarkan produk mereka. Dengan memanfaatkan teknologi, UMKM dapat menjangkau pasar yang lebih luas dan meningkatkan daya saing mereka di pasar global. Teknologi juga memungkinkan UMKM untuk lebih efisien dalam operasional mereka, sehingga dapat menekan biaya dan meningkatkan produktivitas.[/p]\n[p]Pemerintah juga bekerja sama dengan berbagai pihak, termasuk perusahaan teknologi dan lembaga pendidikan, untuk menyediakan pelatihan dan pendampingan bagi UMKM. Dengan demikian, para pelaku UMKM dapat meningkatkan keterampilan mereka dan memanfaatkan teknologi dengan lebih efektif. Semua ini diharapkan dapat membantu UMKM untuk lebih siap menghadapi tantangan di masa depan.[/p]\n[h]Membangun Masa Depan UMKM yang Lebih Baik[/h]\n[p]Dengan adanya regulasi baru ini, diharapkan UMKM di Indonesia dapat lebih tangguh dan mampu bersaing di pasar global. Langkah ini juga menunjukkan komitmen pemerintah dalam mendukung sektor UMKM sebagai salah satu pilar utama perekonomian nasional. Regulasi ini diharapkan dapat memberikan landasan yang kuat bagi perkembangan UMKM di masa depan.[/p]\n[p]Selain itu, regulasi ini juga diharapkan dapat mendorong lebih banyak inovasi di sektor UMKM. Dengan adanya dukungan dari pemerintah, para pelaku UMKM dapat lebih berani untuk mencoba hal-hal baru dan mengembangkan produk-produk yang inovatif. Inovasi ini sangat penting untuk meningkatkan daya saing UMKM di pasar global.[/p]\n[p]Terakhir, regulasi ini juga diharapkan dapat menciptakan lingkungan bisnis yang lebih adil dan kondusif bagi perkembangan UMKM. Dengan adanya perlindungan hukum yang lebih kuat dan dukungan finansial serta teknologi, para pelaku UMKM dapat menjalankan usahanya dengan lebih aman dan nyaman. Semua ini bertujuan untuk menciptakan ekosistem bisnis yang lebih baik bagi UMKM di Indonesia.[/p]",
                'kategori' => 'Produk Hukum',
                'thumbnail' => "https://fastly.picsum.photos/id/24/4855/1803.jpg?hmac=ICVhP1pUXDLXaTkgwDJinSUS59UWalMxf4SOIWb9Ui4",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Program Beasiswa Desa Meningkatkan Akses Pendidikan',
                'slug' => Str::slug('Program Beasiswa Desa Meningkatkan Akses Pendidikan'),
                'preview' => 'Pemerintah desa meluncurkan program beasiswa yang ditujukan untuk siswa berprestasi dari keluarga kurang mampu. Program ini diharapkan dapat meningkatkan akses pendidikan tinggi bagi para pemuda di desa.',
                'konten' => "[h]Beasiswa untuk Siswa Desa[/h]\n[p]Dalam upaya meningkatkan akses pendidikan tinggi bagi para pemuda di desa, pemerintah desa meluncurkan program beasiswa yang ditujukan untuk siswa berprestasi dari keluarga kurang mampu. Program ini diharapkan dapat membuka peluang lebih besar bagi siswa desa untuk melanjutkan pendidikan ke jenjang yang lebih tinggi. Dengan adanya program ini, banyak siswa yang sebelumnya tidak memiliki kesempatan untuk kuliah, kini bisa mengejar cita-cita mereka.[/p]\n[p]Program beasiswa ini mencakup biaya pendidikan, buku, dan biaya hidup selama masa studi. Selain itu, pemerintah desa juga bekerja sama dengan universitas dan lembaga pendidikan untuk memberikan pelatihan dan bimbingan kepada penerima beasiswa. Ini bertujuan agar para penerima beasiswa dapat memanfaatkan kesempatan ini dengan sebaik-baiknya dan mencapai hasil yang optimal.[/p]\n[p]Dengan adanya program beasiswa ini, diharapkan semakin banyak pemuda desa yang dapat meraih cita-citanya dan berkontribusi untuk kemajuan desa mereka di masa depan. Pendidikan adalah kunci untuk membuka banyak peluang, dan program ini diharapkan dapat membantu para siswa desa untuk mencapai potensi penuh mereka.[/p]\n[h]Kerjasama dengan Lembaga Pendidikan[/h]\n[p]Salah satu aspek penting dari program beasiswa ini adalah kerjasama dengan berbagai lembaga pendidikan. Pemerintah desa tidak hanya memberikan dana beasiswa, tetapi juga bekerja sama dengan universitas dan lembaga pelatihan untuk menyediakan program pendidikan yang berkualitas. Kerjasama ini memastikan bahwa para penerima beasiswa mendapatkan pendidikan terbaik yang bisa mereka dapatkan.[/p]\n[p]Selain itu, pemerintah desa juga berupaya untuk menyediakan berbagai program pelatihan dan bimbingan yang dapat membantu para penerima beasiswa untuk mengembangkan keterampilan mereka. Program ini mencakup pelatihan keterampilan teknis dan non-teknis yang relevan dengan kebutuhan pasar kerja. Dengan demikian, para penerima beasiswa tidak hanya mendapatkan pengetahuan akademis, tetapi juga keterampilan praktis yang dapat membantu mereka dalam karier mereka di masa depan.[/p]\n[p]Kerjasama dengan lembaga pendidikan juga mencakup penyediaan berbagai sumber daya dan fasilitas yang dapat mendukung proses belajar para penerima beasiswa. Misalnya, perpustakaan, laboratorium, dan fasilitas penelitian yang bisa digunakan oleh para siswa untuk mendukung studi mereka. Semua ini bertujuan untuk memastikan bahwa para penerima beasiswa mendapatkan pengalaman pendidikan yang komprehensif dan berkualitas tinggi.[/p]",
                'kategori' => 'Pendidikan',
                'thumbnail' => "https://fastly.picsum.photos/id/192/2352/2352.jpg?hmac=jN5UExysObV7_BrOYLdxoDKzm_c_lRM6QkaInKT_1Go",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'PAUD Lestari Kenalkan Pendidikan Lingkungan Sejak...',
                'slug' => Str::slug('PAUD Lestari Kenalkan Pendidikan Lingkungan Sejak..'),
                'preview' => 'Pendidikan Anak Usia Dini (PAUD) Lestari mengadakan kegiatan mengenal lingkungan untuk anak-anak. Kegiatan ini bertujuan untuk menumbuhkan kesadaran tentang pentingnya menjaga alam sejak usia dini...',
                'konten' => "[h]Pendidikan Lingkungan di PAUD[/h]\n[p]PAUD Lestari mengadakan kegiatan pendidikan lingkungan yang bertujuan untuk menumbuhkan kesadaran anak-anak tentang pentingnya menjaga alam sejak usia dini. Kegiatan ini melibatkan anak-anak dalam berbagai aktivitas seperti menanam pohon, merawat tanaman, dan mengenal ekosistem sekitar. Dengan mengenalkan pendidikan lingkungan sejak dini, diharapkan anak-anak akan tumbuh menjadi individu yang peduli dan bertanggung jawab terhadap lingkungan.[/p]\n[p]Selain itu, program ini juga melibatkan para orang tua dalam berbagai kegiatan edukatif. Dengan melibatkan orang tua, diharapkan nilai-nilai tentang pentingnya menjaga lingkungan dapat ditanamkan lebih kuat dan konsisten di rumah. Orang tua juga diberikan pelatihan tentang cara mendukung anak-anak mereka dalam kegiatan-kegiatan lingkungan di rumah.[/p]\n[p]Pendidikan lingkungan di PAUD Lestari juga mencakup pengenalan terhadap berbagai isu lingkungan global. Anak-anak diajak untuk memahami tentang perubahan iklim, konservasi keanekaragaman hayati, dan pentingnya daur ulang. Dengan memahami isu-isu ini sejak dini, diharapkan anak-anak akan tumbuh menjadi generasi yang lebih peka terhadap masalah lingkungan dan lebih proaktif dalam mencari solusi.[/p]\n[h]Kegiatan Praktis untuk Anak-anak[/h]\n[p]PAUD Lestari juga mengadakan berbagai kegiatan praktis yang dapat diikuti oleh anak-anak untuk mengenal lingkungan. Misalnya, mereka diajak untuk menanam pohon di sekitar sekolah, merawat taman sekolah, dan mempelajari cara membuat kompos dari sisa-sisa makanan. Kegiatan-kegiatan ini tidak hanya mengajarkan anak-anak tentang pentingnya menjaga lingkungan, tetapi juga memberikan mereka keterampilan praktis yang berguna.[/p]\n[p]Selain itu, anak-anak juga diajak untuk berpartisipasi dalam kegiatan-kegiatan yang melibatkan komunitas sekitar. Misalnya, mereka ikut serta dalam program pembersihan lingkungan di sekitar tempat tinggal mereka, atau berpartisipasi dalam kampanye-kampanye lingkungan yang diadakan oleh komunitas. Dengan melibatkan anak-anak dalam kegiatan-kegiatan ini, diharapkan mereka dapat merasakan bahwa mereka juga memiliki peran dalam menjaga lingkungan.[/p]\n[p]Kegiatan praktis ini juga membantu anak-anak untuk memahami hubungan antara manusia dan alam secara lebih mendalam. Mereka belajar bahwa setiap tindakan kecil yang mereka lakukan, seperti tidak membuang sampah sembarangan atau menghemat air, dapat memberikan dampak positif bagi lingkungan. Dengan memahami hubungan ini, diharapkan anak-anak akan lebih termotivasi untuk menjaga lingkungan.[/p]\n[h]Manfaat Jangka Panjang Pendidikan Lingkungan[/h]\n[p]Pendidikan lingkungan yang diberikan sejak dini di PAUD Lestari diharapkan dapat memberikan manfaat jangka panjang. Dengan menanamkan nilai-nilai tentang pentingnya menjaga lingkungan sejak dini, diharapkan anak-anak akan tumbuh menjadi individu yang lebih peduli dan bertanggung jawab terhadap lingkungan. Ini akan berdampak positif bagi upaya pelestarian lingkungan di masa depan.[/p]\n[p]Selain itu, pendidikan lingkungan juga dapat membantu membentuk karakter anak-anak. Dengan belajar tentang pentingnya menjaga alam, anak-anak dapat mengembangkan sikap-sikap positif seperti kepedulian, tanggung jawab, dan kerjasama. Sikap-sikap ini sangat penting untuk kehidupan mereka di masa depan, baik dalam konteks pribadi maupun sosial.[/p]\n[p]Manfaat lainnya adalah peningkatan kualitas hidup di masyarakat secara keseluruhan. Dengan adanya generasi yang lebih sadar lingkungan, diharapkan akan ada lebih banyak inisiatif-inisiatif untuk menjaga dan melestarikan lingkungan. Ini akan berdampak positif bagi kesehatan dan kesejahteraan masyarakat, serta keberlanjutan lingkungan di masa depan. Dengan demikian, pendidikan lingkungan yang diberikan sejak dini di PAUD Lestari tidak hanya memberikan manfaat bagi anak-anak secara individu, tetapi juga bagi masyarakat dan lingkungan secara keseluruhan.[/p]",
                'kategori' => 'Pendidikan',
                'thumbnail' => "https://fastly.picsum.photos/id/361/5000/3333.jpg?hmac=XLgLKar1Bg3tKSqrrdfsBC1SUPoiCyRmtP35fSQOSOM",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Inovasi Teknologi Pertanian di Desa Tumbuh Pesat',
                'slug' => Str::slug('Inovasi Teknologi Pertanian di Desa Tumbuh Pesat'),
                'preview' => 'Desa Tumbuh Pesat mengadopsi teknologi pertanian terbaru untuk meningkatkan hasil panen dan kesejahteraan petani. Program ini mendapat sambutan positif dari masyarakat dan menjadi contoh bagi desa lain...',
                'konten' => "[h]Adopsi Teknologi Pertanian[/h]\n[p]Desa Tumbuh Pesat telah mengadopsi berbagai teknologi pertanian terbaru untuk meningkatkan hasil panen dan kesejahteraan petani. Teknologi ini mencakup penggunaan drone untuk pemantauan lahan, sistem irigasi otomatis, dan aplikasi berbasis internet untuk manajemen pertanian. Dengan teknologi ini, petani dapat mengelola lahan mereka dengan lebih efisien dan efektif.[/p]\n[p]Selain itu, teknologi pertanian juga membantu petani dalam mengidentifikasi masalah tanaman lebih cepat dan tepat. Misalnya, penggunaan sensor tanah dapat memberikan informasi tentang kondisi tanah dan kebutuhan nutrisi tanaman. Hal ini memungkinkan petani untuk mengambil tindakan yang tepat waktu dan sesuai kebutuhan, sehingga meningkatkan produktivitas tanaman.[/p]\n[p]Program adopsi teknologi ini juga mendapat dukungan penuh dari pemerintah daerah. Pemerintah menyediakan pelatihan dan pendampingan bagi petani untuk memastikan mereka dapat memanfaatkan teknologi ini dengan baik. Dukungan ini sangat penting untuk memastikan keberhasilan program dan keberlanjutan adopsi teknologi pertanian di desa.[/p]\n[h]Dampak Positif bagi Petani[/h]\n[p]Penerapan teknologi pertanian di Desa Tumbuh Pesat telah memberikan dampak positif yang signifikan bagi para petani. Hasil panen meningkat secara signifikan, yang berarti pendapatan petani juga meningkat. Dengan pendapatan yang lebih tinggi, petani dapat meningkatkan kualitas hidup mereka dan keluarga mereka.[/p]\n[p]Selain itu, teknologi pertanian juga membantu mengurangi beban kerja petani. Misalnya, dengan sistem irigasi otomatis, petani tidak perlu lagi menghabiskan banyak waktu dan tenaga untuk menyirami tanaman. Mereka bisa fokus pada aktivitas lain yang juga penting untuk meningkatkan hasil pertanian.[/p]\n[p]Teknologi pertanian juga membantu petani dalam menghadapi perubahan iklim. Dengan data yang akurat dan real-time, petani dapat membuat keputusan yang lebih baik dalam menghadapi kondisi cuaca yang tidak menentu. Ini sangat penting untuk mengurangi risiko gagal panen dan kerugian finansial yang dapat diakibatkannya.[/p]",
                'kategori' => 'Teknologi',
                'thumbnail' => "https://fastly.picsum.photos/id/277/5000/3333.jpg?hmac=MMop5h2SxxGwjWrUDwakekxLvHNUOG_d9wRUYgvINhU",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'UMKM Desa Berkembang Berkat Pelatihan Digital',
                'slug' => Str::slug('UMKM Desa Berkembang Berkat Pelatihan Digital'),
                'preview' => 'Pelatihan digital yang diadakan oleh pemerintah desa berhasil membantu para pelaku UMKM mengembangkan usaha mereka secara online. Banyak UMKM yang kini mampu menjangkau pasar yang lebih luas...',
                'konten' => "[h]Pelatihan Digital untuk UMKM[/h]\n[p]Pelatihan digital yang diadakan oleh pemerintah desa berhasil membantu para pelaku UMKM mengembangkan usaha mereka secara online. Dengan memanfaatkan teknologi, para pengusaha kecil ini mampu menjangkau pasar yang lebih luas dan meningkatkan penjualan. Pelatihan ini mencakup berbagai topik, mulai dari pemasaran digital, manajemen bisnis online, hingga penggunaan media sosial untuk promosi.[/p]\n[p]Salah satu peserta pelatihan, Ibu Rina, berhasil meningkatkan omzet usahanya hingga dua kali lipat setelah mengikuti pelatihan. Dengan bimbingan dari para mentor, ia belajar cara membuat website dan mengelola toko online. Kini, produk-produknya bisa diakses oleh pelanggan dari berbagai daerah.[/p]\n[p]Keberhasilan pelatihan ini menunjukkan bahwa teknologi dapat menjadi alat yang efektif untuk mendukung perkembangan UMKM. Pemerintah desa berencana untuk terus mengadakan program serupa di masa depan, agar lebih banyak UMKM yang bisa merasakan manfaatnya.[/p]\n[h]Dukungan Pemerintah Desa[/h]\n[p]Selain pelatihan, pemerintah desa juga memberikan berbagai bentuk dukungan kepada para pelaku UMKM. Salah satunya adalah akses permodalan dengan bunga rendah yang memungkinkan UMKM untuk mengembangkan usaha tanpa terbebani biaya tinggi. Program ini diharapkan dapat meningkatkan daya saing UMKM di pasar nasional.[/p]\n[p]Pemerintah desa juga menyediakan pusat layanan bisnis yang dilengkapi dengan berbagai fasilitas, seperti ruang kerja bersama dan akses internet gratis. Pusat layanan ini menjadi tempat bagi para pelaku UMKM untuk bertukar ide dan bekerja sama dalam mengembangkan usaha mereka.[/p]\n[p]Dengan dukungan yang berkelanjutan, diharapkan UMKM di desa dapat terus berkembang dan memberikan kontribusi positif bagi perekonomian lokal. Pemerintah desa berkomitmen untuk selalu mendampingi dan mendukung para pelaku UMKM dalam menghadapi berbagai tantangan bisnis.[/p]",
                'kategori' => 'UMKM',
                'thumbnail' => "https://fastly.picsum.photos/id/48/5000/3333.jpg?hmac=y3_1VDNbhii0vM_FN6wxMlvK27vFefflbUSH06z98so",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Desa Wisata Lestari: Menggali Potensi Sejarah Lokal',
                'slug' => Str::slug('Desa Wisata Lestari: Menggali Potensi Sejarah Lokal'),
                'preview' => 'Desa Wisata Lestari menawarkan pengalaman wisata yang unik dengan menggabungkan keindahan alam dan kekayaan sejarah lokal. Pengunjung dapat belajar tentang sejarah desa sambil menikmati pemandangan alam yang indah...',
                'konten' => "[h]Keindahan Alam Desa[/h]\n[p]Desa Wisata Lestari menawarkan pengalaman wisata yang unik dengan menggabungkan keindahan alam dan kekayaan sejarah lokal. Terletak di kawasan yang masih asri, desa ini menyajikan pemandangan alam yang memukau dengan hutan lebat dan sungai jernih. Pengunjung dapat melakukan berbagai aktivitas alam seperti hiking, bersepeda, dan berkemah sambil menikmati keindahan alam.[/p]\n[p]Selain itu, desa ini juga memiliki sejumlah tempat bersejarah yang menarik untuk dikunjungi. Salah satunya adalah situs peninggalan kerajaan kuno yang masih terjaga dengan baik. Di sini, pengunjung bisa belajar tentang sejarah dan budaya lokal yang kaya akan tradisi dan cerita rakyat.[/p]\n[p]Dengan menggabungkan keindahan alam dan kekayaan sejarah, Desa Wisata Lestari menjadi destinasi yang cocok untuk wisata edukatif dan rekreasi. Pengunjung bisa menikmati keindahan alam sekaligus mendapatkan pengetahuan baru tentang sejarah dan budaya setempat.[/p]",
                'kategori' => 'Wisata dan Sejarah',
                'thumbnail' => "https://img.freepik.com/free-photo/beauty-woman-posing-rise-nature-bali_1296-889.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Galeri Desa Menampilkan Karya Seni Lokal',
                'slug' => Str::slug('Galeri Desa Menampilkan Karya Seni Lokal'),
                'preview' => 'Galeri Desa menjadi tempat bagi para seniman lokal untuk menampilkan karya-karya mereka. Pengunjung dapat menikmati berbagai jenis seni mulai dari lukisan, patung, hingga kerajinan tangan tradisional...',
                'konten' => "[h]Seni Lukis dan Patung[/h]\n[p]Galeri Desa menjadi tempat bagi para seniman lokal untuk menampilkan karya-karya mereka. Di sini, pengunjung bisa menikmati berbagai jenis seni mulai dari lukisan, patung, hingga kerajinan tangan tradisional. Setiap karya seni yang dipamerkan memiliki ciri khas dan keunikan tersendiri, mencerminkan budaya dan kreativitas masyarakat setempat.[/p]\n[p]Salah satu karya yang menarik perhatian adalah lukisan mural besar yang menggambarkan kehidupan sehari-hari di desa. Lukisan ini penuh dengan warna dan detail, memberikan gambaran tentang keragaman budaya dan tradisi lokal. Selain itu, terdapat juga patung-patung kayu yang diukir dengan tangan yang sangat halus dan indah.[/p]\n[p]Kerajinan tangan tradisional seperti anyaman bambu dan tenun juga menjadi bagian dari pameran. Produk-produk ini tidak hanya menunjukkan keahlian para pengrajin, tetapi juga nilai-nilai budaya yang diwariskan dari generasi ke generasi. Pengunjung bisa membeli karya-karya ini sebagai oleh-oleh atau hiasan rumah.[/p]\n[h]Pameran Seni Rupa[/h]\n[p]Galeri Desa sering mengadakan pameran seni rupa yang mengangkat tema-tema lokal. Pameran ini tidak hanya menampilkan karya seni visual, tetapi juga melibatkan pertunjukan seni pertunjukan seperti tarian dan musik tradisional. Acara ini menjadi ajang bagi seniman lokal untuk menunjukkan bakat dan kreativitas mereka kepada masyarakat luas.[/p]\n[p]Pameran seni rupa di Galeri Desa selalu mendapatkan sambutan hangat dari pengunjung. Banyak yang merasa terinspirasi oleh karya-karya yang dipamerkan dan menghargai upaya para seniman dalam melestarikan budaya lokal. Pameran ini juga menjadi sarana edukasi bagi generasi muda untuk mengenal dan mencintai seni tradisional.[/p]",
                'kategori' => 'Galeri Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/vibrant-colors-explode-messy-watercolor-blob-generated-by-ai_188544-9791.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'PKK Desa Gelar Pelatihan Kesehatan untuk Ibu dan Anak',
                'slug' => Str::slug('PKK Desa Gelar Pelatihan Kesehatan untuk Ibu dan Anak'),
                'preview' => 'Tim Penggerak PKK Desa mengadakan pelatihan kesehatan yang fokus pada kesejahteraan ibu dan anak. Pelatihan ini mencakup topik seperti nutrisi, kesehatan ibu hamil, perawatan anak, dan sosialisasi kesehatan...',
                'konten' => "[h]Pelatihan Kesehatan untuk Ibu dan Anak[/h]\n[p]Tim Penggerak PKK Desa mengadakan pelatihan kesehatan yang fokus pada kesejahteraan ibu dan anak. Pelatihan ini mencakup berbagai topik penting seperti nutrisi yang seimbang, kesehatan ibu hamil, dan perawatan anak. Para peserta mendapatkan informasi dan pengetahuan yang berguna untuk menjaga kesehatan keluarga mereka.[/p]\n[p]Salah satu sesi yang sangat diminati adalah tentang nutrisi bagi ibu hamil dan anak-anak. Para ibu diajarkan tentang pentingnya memberikan makanan bergizi untuk mendukung pertumbuhan dan perkembangan anak. Mereka juga mendapatkan resep makanan sehat yang mudah dibuat di rumah.[/p]\n[p]Pelatihan ini juga membahas tentang perawatan kesehatan bagi ibu hamil, termasuk cara-cara mengatasi masalah umum selama kehamilan dan pentingnya pemeriksaan rutin. Dengan pengetahuan ini, diharapkan para ibu dapat menjalani kehamilan yang sehat dan melahirkan bayi yang sehat.[/p]",
                'kategori' => 'PKK Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/silhouette-mother-playing-with-her-son-meadow_1150-414.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'KPMD Desa Tingkatkan Partisipasi Masyarakat dalam pembangunan desa',
                'slug' => Str::slug('KPMD Desa Tingkatkan Partisipasi Masyarakat dalam..'),
                'preview' => 'Kelompok Pemberdayaan Masyarakat Desa (KPMD) aktif mengajak warga untuk berpartisipasi dalam berbagai program pembangunan desa. Kegiatan ini bertujuan untuk meningkatkan kesejahteraan dan kualitas hidup masyarakat desa...',
                'konten' => "[h]Pemberdayaan Masyarakat Desa[/h]\n[p]Kelompok Pemberdayaan Masyarakat Desa (KPMD) aktif mengajak warga untuk berpartisipasi dalam berbagai program pembangunan desa. Kegiatan ini bertujuan untuk meningkatkan kesejahteraan dan kualitas hidup masyarakat desa. Melalui partisipasi aktif, warga desa dapat ikut serta dalam proses pengambilan keputusan dan pelaksanaan program-program yang bermanfaat bagi mereka.[/p]\n[p]Salah satu program yang berhasil dilaksanakan adalah pembangunan fasilitas umum seperti jalan desa dan pusat kesehatan. Dengan melibatkan warga dalam proses pembangunan, hasil yang dicapai menjadi lebih optimal dan sesuai dengan kebutuhan masyarakat. Selain itu, partisipasi masyarakat juga meningkatkan rasa memiliki dan tanggung jawab terhadap fasilitas yang dibangun.[/p]\n[p]KPMD juga mengadakan berbagai pelatihan dan workshop untuk meningkatkan keterampilan dan pengetahuan warga. Program ini mencakup berbagai bidang seperti pertanian, peternakan, dan kerajinan tangan. Dengan keterampilan baru yang diperoleh, warga desa dapat meningkatkan produktivitas dan pendapatan mereka.[/p]",
                'kategori' => 'Pemberdayaan Masyarakat',
                'thumbnail' => "https://img.freepik.com/free-photo/bottom-view-women-protesting-outdoors_23-2150246584.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'LKMD Desa Kembangkan Program Ketahanan Pangan',
                'slug' => Str::slug('LKMD Desa Kembangkan Program Ketahanan Pangan'),
                'preview' => 'Lembaga Ketahanan Masyarakat Desa (LKMD) meluncurkan program ketahanan pangan yang berfokus pada pemanfaatan lahan kosong untuk pertanian. Program ini diharapkan dapat meningkatkan kemandirian pangan di desa...',
                'konten' => "[h]Program Ketahanan Pangan[/h]\n[p]Lembaga Ketahanan Masyarakat Desa (LKMD) meluncurkan program ketahanan pangan yang berfokus pada pemanfaatan lahan kosong untuk pertanian. Tujuan dari program ini adalah meningkatkan kemandirian pangan di desa dengan melibatkan warga dalam berbagai kegiatan pertanian seperti penanaman dan perawatan tanaman.[/p]\n[p]Diharapkan dengan adanya program ini, masyarakat desa dapat memiliki cadangan pangan yang cukup untuk memenuhi kebutuhan sehari-hari serta meningkatkan ekonomi melalui hasil pertanian yang dihasilkan.[/p]",
                'kategori' => 'LKMD Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/collection-common-food-allergens-people_23-2149870525.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'BPD Desa Usulkan Pembangunan Infrastruktur Baru',
                'slug' => Str::slug('BPD Desa Usulkan Pembangunan Infrastruktur Baru'),
                'preview' => 'Badan Permusyawaratan Desa (BPD) mengusulkan beberapa proyek pembangunan infrastruktur untuk meningkatkan aksesibilitas dan kesejahteraan warga desa. Usulan ini mencakup pembangunan jalan, jembatan, dan fasilitas umum lainnya...',
                'konten' => "[h]Usulan Pembangunan Infrastruktur Baru[/h]\n[p]Badan Permusyawaratan Desa (BPD) mengusulkan beberapa proyek pembangunan infrastruktur untuk meningkatkan aksesibilitas dan kesejahteraan warga desa. Usulan ini mencakup pembangunan jalan, jembatan, dan fasilitas umum lainnya yang diharapkan dapat mempermudah mobilitas dan meningkatkan kualitas hidup masyarakat desa.[/p]\n[p]Dengan dukungan dari seluruh elemen masyarakat, diharapkan proyek ini dapat segera direalisasikan untuk kepentingan bersama dan peningkatan pembangunan desa secara keseluruhan.[/p]",
                'kategori' => 'BPD Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/construction-silhouette_1150-8336.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Kuliner Desa: Nikmati Kelezatan Masakan Tradisional',
                'slug' => Str::slug('Kuliner Desa: Nikmati Kelezatan Masakan Tradisional'),
                'preview' => 'Desa Kuliner menghadirkan berbagai macam masakan tradisional yang menggugah selera. Setiap hidangan disiapkan dengan resep turun-temurun yang menjaga cita rasa asli dari masakan nusantara...',
                'konten' => "[h]Kuliner Desa[/h]\n[p]Desa Kuliner menghadirkan berbagai macam masakan tradisional yang menggugah selera. Setiap hidangan disiapkan dengan resep turun-temurun yang menjaga cita rasa asli, memberikan pengalaman kuliner yang unik bagi pengunjung.[/p]\n[p]Selain mengembangkan warisan kuliner lokal, inisiatif ini juga berkontribusi pada perekonomian lokal dengan membuka lapangan pekerjaan baru dan meningkatkan pendapatan bagi pelaku usaha kuliner di desa.[/p]",
                'kategori' => 'Kuliner',
                'thumbnail' => "https://img.freepik.com/free-photo/rice-noodles-bowl-curry-paste-with-chili-cucumber-long-bean-lime-garlic-spring-onion_1150-27067.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Oleh-Oleh Khas Desa yang Wajib Dibawa Pulang',
                'slug' => Str::slug('Oleh-Oleh Khas Desa yang Wajib Dibawa Pulang'),
                'preview' => 'Berkunjung ke desa ini belum lengkap tanpa membawa pulang oleh-oleh khas yang terkenal. Produk oleh-oleh meliputi makanan ringan, kerajinan tangan, dan produk lokal lainnya yang unik dan berkualitas...',
                'konten' => "[h]Oleh-Oleh Khas Desa[/h]\n[p]Berkunjung ke desa ini belum lengkap tanpa membawa pulang oleh-oleh khas yang terkenal. Produk oleh-oleh meliputi makanan ringan, kerajinan tangan, dan produk lokal lainnya yang unik dan berkualitas, menjadi pilihan yang tepat untuk dijadikan kenang-kenangan dari perjalanan Anda.[/p]\n[p]Selain sebagai bukti kunjungan, oleh-oleh khas desa juga merupakan salah satu cara untuk mendukung ekonomi lokal dan melestarikan budaya dan tradisi masyarakat desa.[/p]",
                'kategori' => 'Oleh-oleh',
                'thumbnail' => "https://img.freepik.com/free-photo/baskets-sale_1398-2316.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Kerajinan Tangan Desa: Kreativitas Tanpa Batas',
                'slug' => Str::slug('Kerajinan Tangan Desa: Kreativitas Tanpa Batas'),
                'preview' => 'Pengrajin desa menghasilkan berbagai kerajinan tangan yang memukau. Dari anyaman bambu hingga ukiran kayu, setiap karya menunjukkan kreativitas dan keahlian tinggi para pengrajin lokal...',
                'konten' => "[h]Kerajinan Tangan Desa[/h]\n[p]Pengrajin desa menghasilkan berbagai kerajinan tangan yang memukau. Dari anyaman bambu hingga ukiran kayu, setiap karya menunjukkan kreativitas dan keahlian tinggi para pengrajin lokal. Produk kerajinan tangan ini tidak hanya memperindah rumah Anda, tetapi juga menjadi bukti nyata dari kekayaan seni dan budaya masyarakat desa.[/p]\n[p]Dukungan terhadap kerajinan tangan lokal tidak hanya memperkuat identitas budaya, tetapi juga membuka peluang ekonomi baru bagi pengrajin desa untuk meningkatkan kesejahteraan mereka.[/p]",
                'kategori' => 'Kerajinan Tangan',
                'thumbnail' => "https://img.freepik.com/free-photo/texture-background_1404-179.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Bangkit dari Keterpurukan: Kisah Inspiratif Petani Desa',
                'slug' => Str::slug('Bangkit dari Keterpurukan: Kisah Inspiratif Petani Desa'),
                'preview' => 'Kisah seorang petani desa yang berhasil bangkit dari keterpurukan setelah gagal panen berulang kali. Dengan tekad kuat dan semangat pantang menyerah, ia kini sukses dengan metode pertanian organik...',
                'konten' => "[h]Kisah Inspiratif[/h]\n[p]Seorang petani di desa ini mengalami masa-masa sulit ketika gagal panen berulang kali. Namun, ia tidak menyerah begitu saja. Dengan tekad kuat, dia mulai mencoba metode pertanian organik yang ramah lingkungan dan lebih berkelanjutan.[/p]\n[h]Perjuangan dan Keberhasilan[/h]\n[p]Setelah melewati banyak tantangan, petani ini akhirnya berhasil mengubah keadaan. Hasil pertaniannya semakin baik dan kini dia menjadi contoh inspiratif bagi masyarakat desa lainnya.[/p]\n[p]Keberhasilannya tidak hanya dalam segi pertanian, tetapi juga dalam mempertahankan semangat untuk terus berusaha dan tidak menyerah dalam menghadapi kesulitan hidup.[/p]\n[p]Kisah ini mengajarkan kita tentang pentingnya ketekunan dan semangat pantang menyerah dalam mencapai tujuan hidup.[/p]",
                'kategori' => 'Motivasi',
                'thumbnail' => "https://img.freepik.com/free-photo/male-farmer-who-is-using-shovel-dig-soil-his-rice-fields_1150-17239.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Peraturan Desa Baru untuk Perlindungan Lingkungan',
                'slug' => Str::slug('Peraturan Desa Baru untuk Perlindungan Lingkungan'),
                'preview' => 'Desa Lestari menetapkan peraturan baru yang ketat untuk menjaga kelestarian lingkungan. Peraturan ini mencakup larangan penebangan liar dan pembuangan sampah sembarangan, serta kewajiban bagi warga untuk menanam...',
                'konten' => "[h]Perlindungan Lingkungan[/h]\n[p]Desa Lestari telah mengambil langkah serius dalam menjaga kelestarian lingkungan dengan menetapkan peraturan baru. Peraturan ini melarang aktivitas penebangan liar yang merusak hutan serta pembuangan sampah sembarangan yang dapat merusak ekosistem lokal.[/p]\n[p]Selain itu, setiap warga diwajibkan untuk menanam pohon setiap tahun sebagai bagian dari upaya peningkatan tutupan hijau dan mengurangi jejak karbon di desa ini.[/p]\n[h]Dampak Positif[/h]\n[p]Keputusan ini tidak hanya memberikan perlindungan bagi lingkungan hidup saat ini, tetapi juga meninggalkan warisan yang berharga bagi generasi mendatang untuk menikmati keindahan alam dan sumber daya alam yang berlimpah.[/p]",
                'kategori' => 'Produk Hukum',
                'thumbnail' => "https://fastly.picsum.photos/id/353/5000/2806.jpg?hmac=QvrRaGlMinnGfuGM-yhcEwdMbIM3MXXyo0dC7PqqGc0",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Kelas Online Gratis untuk Siswa Desa Terpencil',
                'slug' => Str::slug('Kelas Online Gratis untuk Siswa Desa Terpencil'),
                'preview' => 'Dalam upaya meningkatkan akses pendidikan, desa terpencil mengadakan kelas online gratis bagi siswa. Program ini bekerja sama dengan universitas terkemuka dan diharapkan dapat membantu siswa mendapatkan pendidikan berkualitas...',
                'konten' => "[h]Pendidikan untuk Semua[/h]\n[p]Di tengah tantangan aksesibilitas, desa terpencil ini memutuskan untuk menyediakan kesempatan belajar online gratis bagi siswa. Langkah ini diambil untuk memastikan bahwa setiap anak memiliki akses yang sama terhadap pendidikan berkualitas tanpa terbatas oleh geografis atau ekonomi.[/p]\n[p]Program ini berkolaborasi dengan universitas terkemuka dalam memberikan konten pembelajaran yang relevan dan up to date, sehingga siswa dapat belajar dengan metode terbaik yang tersedia saat ini.[/p]\n[h]Dukungan Komunitas[/h]\n[p]Keberhasilan program ini tidak hanya bergantung pada penyelenggaraannya, tetapi juga dukungan dari seluruh komunitas untuk memastikan setiap siswa dapat mengakses dan memanfaatkan kesempatan belajar ini dengan baik.[/p]\n[p]Inisiatif ini diharapkan dapat menjadi tonggak baru dalam meningkatkan tingkat pendidikan dan kualitas hidup di desa-desa terpencil sekitarnya.[/p]",
                'kategori' => 'Pendidikan',
                'thumbnail' => "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'PAUD Lestari Adakan Festival Kreativitas Anak',
                'slug' => Str::slug('PAUD Lestari Adakan Festival Kreativitas Anak'),
                'preview' => 'PAUD Lestari mengadakan festival kreativitas yang melibatkan anak-anak dalam berbagai kegiatan seni dan kerajinan. Acara ini bertujuan untuk mengembangkan bakat dan minat anak sejak dini mulai dari...',
                'konten' => "[h]Festival Kreativitas Anak[/h]\n[p]PAUD Lestari menyelenggarakan festival kreativitas tahunan yang dihadiri oleh anak-anak dari desa sekitar. Acara ini dirancang untuk mengembangkan bakat dan minat anak-anak dalam berbagai kegiatan seni dan kerajinan tangan.[/p]\n[p]Melalui festival ini, anak-anak diberi kesempatan untuk mengeksplorasi kreativitas mereka dan menunjukkan bakat yang dimiliki di hadapan orang tua dan masyarakat desa.[/p]\n[h]Manfaat Festival[/h]\n[p]Selain sebagai sarana hiburan dan edukasi, festival ini juga bertujuan untuk memperkuat rasa percaya diri anak-anak serta mempererat hubungan antargenerasi dalam masyarakat desa.[/p]\n[p]Dengan mengapresiasi dan mendukung potensi kreatif anak-anak, PAUD Lestari berharap dapat menciptakan generasi penerus yang berbakat dan berdaya saing tinggi.[/p]",
                'kategori' => 'Pendidikan',
                'thumbnail' => "https://img.freepik.com/free-photo/group-kids-friend-laughing-together_1150-3911.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Desa Pintar: Menggunakan IoT untuk Meningkatkan Kualitas Hidup Warga',
                'slug' => Str::slug('Desa Pintar: Menggunakan IoT untuk Meningkatkan Kualitas Hidup'),
                'preview' => 'Desa Pintar mengadopsi teknologi Internet of Things (IoT) untuk meningkatkan kualitas hidup warga. Dari pemantauan kesehatan hingga pengelolaan sumber daya air, teknologi ini memberikan banyak manfaat bagi masy...',
                'konten' => "[h]Desa Pintar dan Teknologi IoT[/h]\n[p]Desa Pintar adalah konsep pengembangan desa yang mengintegrasikan teknologi Internet of Things (IoT) untuk meningkatkan kualitas hidup warga. Teknologi ini memungkinkan pengumpulan data yang akurat dan real-time tentang berbagai aspek kehidupan desa, termasuk pemantauan kesehatan, keamanan, dan pengelolaan sumber daya alam.[/p]\n[h]Manfaat bagi Masyarakat Desa[/h]\n[p]Dengan adopsi teknologi ini, masyarakat desa dapat mengoptimalkan penggunaan sumber daya, mengurangi pemborosan, dan meningkatkan efisiensi dalam berbagai kegiatan sehari-hari. Contohnya termasuk pengelolaan irigasi pertanian yang lebih efisien dan pemantauan kualitas air untuk kebutuhan masyarakat.[/p]\n[p]Desa Pintar tidak hanya meningkatkan kenyamanan hidup warga, tetapi juga membuka peluang untuk pengembangan lebih lanjut dalam infrastruktur dan layanan teknologi di masa depan.[/p]",
                'kategori' => 'Teknologi',
                'thumbnail' => "https://fastly.picsum.photos/id/160/3200/2119.jpg?hmac=cz68HnnDt3XttIwIFu5ymcvkCp-YbkEBAM-Zgq-4DHE",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'UMKM Desa Raih Penghargaan Berkat Inovasi Produk',
                'slug' => Str::slug('UMKM Desa Raih Penghargaan Berkat Inovasi Produk'),
                'preview' => 'Sebuah UMKM di desa ini meraih penghargaan bergengsi atas inovasi produknya yang unik dan ramah lingkungan. Penghargaan ini menjadi motivasi bagi pelaku UMKM lain untuk terus berinovasi dan berkembang...',
                'konten' => "[h]UMKM Desa Raih Penghargaan[/h]\n[p]Sebuah Usaha Mikro Kecil Menengah (UMKM) di desa ini baru-baru ini meraih penghargaan prestisius atas inovasi produknya yang unik dan ramah lingkungan. Penghargaan ini diberikan sebagai pengakuan terhadap upaya UMKM dalam meningkatkan kualitas produk dan mendorong inovasi di tingkat lokal.[/p]\n[p]Prestasi ini menjadi motivasi besar bagi pelaku UMKM lainnya di desa untuk terus mengembangkan kreativitas dan inovasi dalam produk mereka. Hal ini juga menginspirasi desa lain untuk mengembangkan potensi ekonomi lokal melalui pengembangan UMKM yang berkelanjutan dan berdaya saing tinggi.[/p]",
                'kategori' => 'UMKM',
                'thumbnail' => "https://img.freepik.com/free-photo/making-footwear_1098-13645.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Menyusuri Jejak Sejarah di Desa Tua',
                'slug' => Str::slug('Menyusuri Jejak Sejarah di Desa Tua'),
                'preview' => 'Desa Tua menawarkan tur sejarah yang mengajak pengunjung menyusuri jejak masa lampau. Dengan panduan lokal, pengunjung dapat belajar tentang sejarah desa yang kaya akan peristiwa penting dan budaya unik...',
                'konten' => "[h]Menyusuri Jejak Sejarah di Desa Tua[/h]\n[p]Desa Tua adalah tempat yang kaya akan sejarah, dimana pengunjung diajak untuk menjelajahi jejak masa lampau melalui tur sejarah yang disertai dengan panduan lokal. Di setiap langkahnya, pengunjung dapat belajar lebih dalam tentang peristiwa bersejarah dan kehidupan masyarakat pada masa lalu.[/p]\n[p]Kunjungan ini tidak hanya memberikan pengalaman edukatif, tetapi juga memperkaya pemahaman akan warisan budaya yang masih hidup di desa ini. Hal ini menjadikan Desa Tua sebagai destinasi menarik bagi wisatawan yang tertarik dengan sejarah dan budaya lokal.[/p]",
                'kategori' => 'Wisata dan Sejarah',
                'thumbnail' => "https://img.freepik.com/free-photo/small-houses-hill-forest_181624-30800.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Pameran Seni Rupa di Galeri Desa Angkat Kearifan Lokal',
                'slug' => Str::slug('Pameran Seni Rupa di Galeri Desa Angkat Kearifan Lokal'),
                'preview' => 'Galeri Desa mengadakan pameran seni rupa yang menampilkan karya-karya yang mengangkat kearifan lokal. Pameran ini mendapat apresiasi dari berbagai kalangan dan diharapkan dapat meningkatkan minat masyarakat terhadap seni...',
                'konten' => "[h]Pameran Seni Rupa di Galeri Desa[/h]\n[p]Galeri Desa baru-baru ini menggelar pameran seni rupa yang menghadirkan karya-karya menakjubkan dari seniman lokal yang mengangkat kearifan lokal. Pameran ini tidak hanya menjadi ajang untuk mengapresiasi seni tradisional, tetapi juga meningkatkan kesadaran masyarakat akan nilai-nilai budaya yang diwariskan melalui karya seni.[/p]\n[p]Setiap karya yang dipamerkan memiliki cerita dan makna tersendiri yang mencerminkan kekayaan dan keunikan budaya lokal. Ini juga menjadi kesempatan bagi para seniman untuk mendapatkan pengakuan dan dukungan lebih luas dari komunitas seni lokal maupun internasional.[/p]",
                'kategori' => 'Galeri Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/crop-artist-near-palette_23-2147802031.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'PKK Desa Sukses Gelar Lomba Masak Berbasis Bahan Lokal',
                'slug' => Str::slug('PKK Desa Sukses Gelar Lomba Masak Berbasis Bahan Lokal'),
                'preview' => 'Tim Penggerak PKK Desa sukses menggelar lomba masak yang berbasis bahan lokal. Lomba ini tidak hanya meningkatkan kreativitas ibu-ibu PKK, tetapi juga mempromosikan penggunaan bahan pangan lokal yang sehat dan bernutrisi...',
                'konten' => "[h]Lomba Masak Berbasis Bahan Lokal oleh PKK Desa[/h]\n[p]Tim Penggerak PKK Desa telah berhasil menggelar lomba masak yang bertujuan untuk mempromosikan kekayaan kuliner lokal berbasis bahan pangan lokal. Lomba ini diikuti dengan antusiasme tinggi oleh ibu-ibu PKK yang ingin menunjukkan kreativitas dalam memasak menggunakan bahan-bahan sehat dan bernutrisi.[/p]\n[p]Selain menjadi ajang kompetisi, lomba ini juga menjadi platform untuk mengedukasi masyarakat tentang pentingnya memanfaatkan bahan pangan lokal yang berkelanjutan dan mendukung kesehatan keluarga.[/p]\n[p]Keberhasilan lomba ini tidak hanya terlihat dari kreativitas para peserta, tetapi juga dari dukungan luas yang diberikan oleh masyarakat dalam mendukung promosi dan konsumsi produk lokal.[/p]",
                'kategori' => 'PKK Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/chef-cooking-recipe_23-2148145624.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'KPMD Desa Luncurkan Program Pemberdayaan Wanita',
                'slug' => Str::slug('KPMD Desa Luncurkan Program Pemberdayaan Wanita'),
                'preview' => 'Kelompok Pemberdayaan Masyarakat Desa (KPMD) meluncurkan program pemberdayaan wanita yang fokus pada pelatihan keterampilan dan kewirausahaan. Program ini bertujuan untuk meningkatkan kemandirian ekonomi para wanita...',
                'konten' => "[h]Program Pemberdayaan Wanita oleh KPMD Desa[/h]\n[p]KPMD Desa telah meluncurkan program pemberdayaan wanita yang difokuskan pada pelatihan keterampilan dan kewirausahaan. Program ini bertujuan untuk meningkatkan kemandirian ekonomi para wanita di desa, memungkinkan mereka untuk terlibat dalam berbagai kegiatan ekonomi lokal secara produktif dan mandiri.[/p]\n[p]Selain itu, program ini juga menyediakan pendampingan dan dukungan untuk para peserta dalam mengembangkan usaha kecil dan menengah mereka. Hal ini diharapkan dapat menciptakan lingkungan ekonomi yang inklusif dan memberdayakan perempuan secara sosial dan ekonomi di desa.[/p]\n[p]Dengan adanya program ini, diharapkan akan tercipta generasi perempuan desa yang tangguh dan mampu berkontribusi secara signifikan dalam pembangunan ekonomi lokal serta kesejahteraan keluarga dan komunitas mereka.[/p]",
                'kategori' => 'KPMD Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/japanese-business-concept-with-business-partners_23-2149268062.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'LKMD Desa Adakan Pelatihan Mitigasi Bencana',
                'slug' => Str::slug('LKMD Desa Adakan Pelatihan Mitigasi Bencana'),
                'preview' => 'Lembaga Ketahanan Masyarakat Desa (LKMD) mengadakan pelatihan mitigasi bencana untuk meningkatkan kesiapsiagaan warga dalam menghadapi potensi bencana alam. Pelatihan ini diikuti oleh seluruh warga desa dengan antus...',
                'konten' => "[h]Pelatihan Mitigasi Bencana oleh LKMD Desa[/h]\n[p]Lembaga Ketahanan Masyarakat Desa (LKMD) mengadakan pelatihan mitigasi bencana yang bertujuan untuk meningkatkan kesiapsiagaan warga dalam menghadapi berbagai potensi bencana alam. Pelatihan ini merupakan upaya serius dari LKMD untuk melibatkan seluruh masyarakat dalam upaya pencegahan dan penanggulangan bencana yang lebih efektif.[/p]\n[p]Dengan diikuti oleh seluruh warga desa, pelatihan ini berhasil menciptakan kesadaran kolektif dan kesiapan dalam menghadapi situasi darurat. Antusiasme tinggi dari masyarakat menunjukkan komitmen yang kuat untuk bersama-sama menjaga keamanan dan kesejahteraan desa dari ancaman bencana.[/p]",
                'kategori' => 'LKMD Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/rock-pieces-russian-s-war-ukraine_23-2149437901.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'BPD Desa Gelar Musyawarah Pembangunan Berkelanjutan',
                'slug' => Str::slug('BPD Desa Gelar Musyawarah Pembangunan Berkelanjutan'),
                'preview' => 'Badan Permusyawaratan Desa (BPD) mengadakan musyawarah untuk merencanakan pembangunan berkelanjutan. Musyawarah ini melibatkan seluruh elemen masyarakat dan bertujuan untuk menyusun rencana pembangunan yang berpihak pada...',
                'konten' => "[h]Musyawarah Pembangunan Berkelanjutan oleh BPD Desa[/h]\n[p]Badan Permusyawaratan Desa (BPD) mengadakan musyawarah untuk merencanakan pembangunan yang berkelanjutan dan berpihak pada lingkungan serta kesejahteraan warga desa. Musyawarah ini menjadi forum penting yang melibatkan seluruh elemen masyarakat dalam menyusun rencana pembangunan yang berorientasi pada keberlanjutan dan kesejahteraan bersama.[/p]\n[p]Partisipasi aktif dari berbagai komponen masyarakat, termasuk pemangku kepentingan lokal, menunjukkan keseriusan dan komitmen dalam membangun desa secara berkelanjutan. Rencana yang disusun melalui musyawarah ini diharapkan mampu memberikan dampak positif yang signifikan bagi perkembangan dan kesejahteraan desa di masa depan.[/p]",
                'kategori' => 'BPD Desa',
                'thumbnail' => "https://img.freepik.com/free-photo/project-team-collaborating-business-analytics_1098-19159.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Sajian Khas Desa: Resep Rahasia yang Melegenda',
                'slug' => Str::slug('Sajian Khas Desa: Resep Rahasia yang Melegenda'),
                'preview' => 'Kuliner khas desa ini terkenal dengan resep rahasianya yang telah diwariskan turun-temurun. Setiap suapan membawa cita rasa autentik yang tak terlupakan, menjadikan desa ini destinasi kuliner yang wajib dikunjungi...',
                'konten' => "[h]Sajian Khas Desa: Resep Rahasia yang Melegenda[/h]\n[p]Desa ini terkenal dengan kuliner khasnya yang unik dan autentik, dimana setiap hidangan memiliki resep rahasia yang diwariskan secara turun-temurun. Cita rasa dari masakan tradisional ini tidak hanya memuaskan lidah, tetapi juga membawa pengalaman kuliner yang tak terlupakan bagi para pengunjung.[/p]\n[p]Kuliner khas desa ini telah menjadi daya tarik utama bagi wisatawan yang ingin menikmati kelezatan dari resep tradisional yang masih terjaga keasliannya hingga saat ini. Pengalaman kuliner di desa ini benar-benar memberikan kepuasan tersendiri bagi para pecinta makanan tradisional.[/p]",
                'kategori' => 'Kuliner',
                'thumbnail' => "https://img.freepik.com/free-photo/spicy-fried-basil-leaf-with-chicken-rice_1203-6764.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Oleh-Oleh Desa: Cendera Mata Unik yang Tak Boleh Terlewatkan',
                'slug' => Str::slug('Oleh-Oleh Desa: Cendera Mata Unik yang Tak Boleh Terlewatkan'),
                'preview' => 'Berbagai cendera mata unik yang dibuat oleh para pengrajin desa siap menjadi oleh-oleh yang tak terlupakan. Mulai dari anyaman, ukiran kayu, hingga produk olahan makanan, semuanya menawarkan keunikan tersendiri...',
                'konten' => "[h]Oleh-Oleh Desa: Cendera Mata Unik yang Tak Boleh Terlewatkan[/h]\n[p]Desa ini terkenal dengan berbagai cendera mata unik yang dihasilkan oleh para pengrajin lokal. Mulai dari anyaman tradisional, ukiran kayu, hingga produk olahan makanan yang dibuat dengan tangan dan cinta kasih, setiap oleh-oleh desa ini menawarkan keunikan dan keaslian yang sulit ditemukan di tempat lain.[/p]\n[p]Berbelanja oleh-oleh di desa ini bukan hanya sekedar membeli suvenir, tetapi juga mendukung keberlangsungan kerajinan tangan lokal serta memperkenalkan keindahan dan kekayaan budaya kepada para pengunjung dari berbagai daerah.[/p]",
                'kategori' => 'Oleh-oleh',
                'thumbnail' => "https://img.freepik.com/free-photo/full-frame-cardboard-boxes-with-tag-baby-s-breath-flowers-wooden-backdrop_23-2147936675.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
            [
                'judul' => 'Kerajinan Tangan Desa: Kreativitas di Tengah Keterbatasan',
                'slug' => Str::slug('Kerajinan Tangan Desa: Kreativitas di Tengah Keterbatasan'),
                'preview' => 'Pengrajin desa terus berkarya di tengah keterbatasan, menghasilkan produk-produk kerajinan tangan yang luar biasa. Dari anyaman bambu hingga perhiasan dari bahan daur ulang, kreativitas mereka tidak pernah berhenti...',
                'konten' => "[h]Kerajinan Tangan Desa: Kreativitas di Tengah Keterbatasan[/h]\n[p]Pengrajin desa terus menunjukkan kreativitas yang luar biasa dalam menghasilkan produk-produk kerajinan tangan yang unik dan berkualitas. Meskipun dihadapkan pada keterbatasan sumber daya, mereka berhasil menciptakan produk dari anyaman bambu, kerajinan perhiasan dari bahan daur ulang, dan banyak lagi yang menginspirasi.[/p]\n[p]Kerajinan tangan dari desa ini tidak hanya menawarkan produk berkualitas tinggi, tetapi juga mengandung nilai-nilai keberlanjutan dan kreativitas yang tinggi. Setiap produk merupakan cerminan dari dedikasi dan keuletan pengrajin dalam menjaga warisan budaya dan alam sekitar.[/p]",
                'kategori' => 'Kerajinan Tangan',
                'thumbnail' => "https://img.freepik.com/free-photo/wicker-baskets_1398-2318.jpg",
                'published_datetime' => Carbon::now()->subDays(rand(0, 365)),
                'views' => rand(0, 1000),
            ],
        ]);
    }
}
